### ISSUE TITLE
DAC class in audio engine

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/Maximilian#12]

**Comment by chriskiefer** [comment]
sine(400) >> DAC(0)
sine(20) >> DAC
sine(2349) >> DAC(0,4,5)

**Comment by chriskiefer** [comment]
DAC is a transducer

**Comment by frantic0** [comment]
Useful informative bits
[Audio graphs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Basic_concepts_behind_Web_Audio_API#Audio_graphs
)
[Channels](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Basic_concepts_behind_Web_Audio_API#Audio_buffers_frames_samples_and_channels)
[Up and down-mixing](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Basic_concepts_behind_Web_Audio_API#Up-mixing_and_down-mixing) 

Audio nodes are linked via their inputs and outputs.

Each input or output is composed of one or more audio channels, which together represent a specific audio layout.

When the number of channels doesn't match between an input and an output, up- or down-mixing happens according the following rules. This can be somewhat controlled by setting the **AudioNode.channelInterpretation** property to **speakers** or **discrete**:

**Comment by frantic0** [comment]
// sine(20) >> DAC – Default case, play one channel stereo
    // sine(400) >> DAC(0) – One channel selected, mono
    // sine(2349) >> DAC(0,4,5) – Three channels selected, indidual routing

**Comment by frantic0** [comment]
a DAC, in the worklet processor sandbox context, can only concern the inputs and outputs that are given to the worklet. 

The default case for an app running an waapi graph with our processor connect to the audio destination node in macbookpro w/ default audio interface is:

```inputs 1, outputsLen 1, outputLen 1, outputChannelLen 128``` 

One complex case is we might want to try is building a complex waapi graph with multiple source nodes connecting to it, and output nodes connecting from it.
