### ISSUE TITLE
downsampling to predefined sample rate in audio worklet

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/Maximilian#14]

**Comment by frantic0** [comment]
I sorted this out and updated in following audioWorklet examples:
- maxi-processor-dac
- maxi-processor-eval-message
- maxi-processor-granular
- maxi-processor-hot-swapping-worklets
- maxi-processor-ring-buffer
- maxi-processor-synth-pool

Please review the code and close if agreed
