### ISSUE TITLE
fix up maxiSample to work in c++ and js

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/Maximilian#2]
it's all a mess!

**Comment by frantic0** [comment]
I have problems loading the new m.wasmmodule.js into the worklet. I know for sure it is its inclusion but I can't get any hints about why it is failing (silent error!)

I commented out the maxiSample embinding but it didn't work. 

Next, I will do a manual inspection of the m.wasmmodule.js and compare it with the functional ones.

**Comment by frantic0** [comment]
forget about this, just fixed the bug. back on track again.
