### ISSUE TITLE
SPN version returns a promise

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/Maximilian#32]

**Comment by chriskiefer** [comment]
adding in 				-s WASM_ASYNC_COMPILATION=0  to the build seems to fix this, however emcc documentation warns of potential problems with Chrome:

_```
// Whether to compile the wasm asynchronously, which is more efficient and does
// not block the main thread. This is currently required for all but the
// smallest modules to run in chrome.
//
// (This option was formerly called BINARYEN_ASYNC_COMPILATION)
var WASM_ASYNC_COMPILATION = 1;
```_


Alternatives are:

1. Remove the  WASM_ASYNC_COMPILATION flag and deal with the promise
2. Switch off the modularize flag, in which case we need to refer to Module instead of maximilian()

either way, there would be a breaking change

**Comment by chriskiefer** [comment]
see also the FAQ on modularize https://emscripten.org/docs/getting_started/FAQ.html#how-can-i-tell-when-the-page-is-fully-loaded-and-it-is-safe-to-call-compiled-functions and promises

and the notes on modularize in https://github.com/emscripten-core/emscripten/blob/master/src/settings.js

**Comment by frantic0** [comment]
I'm currently working on this issue on my side and there is a constraint. 

maximilian.wasmmodule.js:1616 failed to compile wasm module: RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.

I believe this means the compilation cannot be synchronous?

**Comment by chriskiefer** [comment]
resolved: we have decided to run with the async promise, for future compatibility.  This is a breaking change to initialising the audio engine, so there are now two ways to start it up:

1.

```
	async function maxi(){
		let m = await maximilian();
			let playAudio = () => {

				let maxiAudio = new m.maxiAudio();
				maxiAudio.init();
				maxiAudio.play = function () {
				}
			}
	 };
	 maxi();
```

2.
```
	maximilian().then( (m) =>{
		let m = await maximilian();
			let playAudio = () => {
				let maxiAudio = new m.maxiAudio();
				maxiAudio.init();
				maxiAudio.play = function () {
				}
			}
	 };

```
