### ISSUE TITLE
memory allocation raise?

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/Maximilian#36]
currently 67108864 - about 0.5 gb - can we afford to raise this?

**Comment by micknoise** [comment]
The version hosted on Luuma.net reports the memory allocation is 16781312 bytes so I think the only problem is that this version may need recompiling?

**Comment by frantic0** [comment]
The ceiling for the WASM heap is 4GB

https://v8.dev/blog/4gb-wasm-memory#:~:text=Thanks%20to%20recent%20work%20in,512MB%20or%201GB%20of%20memory!

**Comment by chriskiefer** [comment]
no raise needed in the end
